INSERT INTO users (
    user_id,
    email,
    full_name,
    role,
    territory_name,
    region_name,
    can_view_wac
) VALUES
('U001', 'sarah.chen@novapharma.com', 'Sarah Chen', 'exec', NULL, NULL, 1),
('U002', 'michael.torres@novapharma.com', 'Michael Torres', 'exec', NULL, NULL, 1),
('U003', 'jennifer.walsh@novapharma.com', 'Jennifer Walsh', 'director', NULL, 'Northeast', 0),
('U004', 'david.park@novapharma.com', 'David Park', 'director', NULL, 'Mid-Atlantic', 0),
('U005', 'lisa.johnson@novapharma.com', 'Lisa Johnson', 'director', NULL, 'Southeast', 0),
('U006', 'robert.kim@novapharma.com', 'Robert Kim', 'director', NULL, 'Midwest', 0),
('U007', 'maria.garcia@novapharma.com', 'Maria Garcia', 'director', NULL, 'South Central', 0),
('U008', 'james.anderson@novapharma.com', 'James Anderson', 'director', NULL, 'West', 0),
('U009', 'amy.nguyen@novapharma.com', 'Amy Nguyen', 'ram', 'New York Metro', 'Northeast', 0),
('U010', 'brian.murphy@novapharma.com', 'Brian Murphy', 'ram', 'New England', 'Northeast', 0),
('U011', 'carlos.rivera@novapharma.com', 'Carlos Rivera', 'ram', 'Mid-Atlantic East', 'Mid-Atlantic', 0),
('U012', 'diana.wright@novapharma.com', 'Diana Wright', 'ram', 'Mid-Atlantic West', 'Mid-Atlantic', 0),
('U013', 'eric.thompson@novapharma.com', 'Eric Thompson', 'ram', 'Southeast Atlantic', 'Southeast', 0),
('U014', 'fiona.davis@novapharma.com', 'Fiona Davis', 'ram', 'Southeast Gulf', 'Southeast', 0),
('U015', 'george.martinez@novapharma.com', 'George Martinez', 'ram', 'Great Lakes East', 'Midwest', 0),
('U016', 'hannah.lee@novapharma.com', 'Hannah Lee', 'ram', 'Great Lakes West', 'Midwest', 0),
('U017', 'ivan.petrov@novapharma.com', 'Ivan Petrov', 'ram', 'Upper Midwest', 'Midwest', 0),
('U018', 'julia.robinson@novapharma.com', 'Julia Robinson', 'ram', 'Texas', 'South Central', 0),
('U019', 'kevin.brown@novapharma.com', 'Kevin Brown', 'ram', 'South Central', 'South Central', 0),
('U020', 'laura.wilson@novapharma.com', 'Laura Wilson', 'ram', 'Pacific Northwest', 'West', 0),
('U021', 'nathan.clark@novapharma.com', 'Nathan Clark', 'ram', 'California North', 'West', 0),
('U022', 'olivia.taylor@novapharma.com', 'Olivia Taylor', 'ram', 'California South', 'West', 0),
('U023', 'patrick.moore@novapharma.com', 'Patrick Moore', 'ram', 'Mountain', 'West', 0);
