BEGIN;

CREATE TABLE organizations (
    org_id                  text PRIMARY KEY,
    org_name                text NOT NULL,
    org_type                text NOT NULL CHECK (
        org_type IN ('Facility', 'Parent', 'Grandparent', 'GPO', 'Payer')
    ),
    org_status              text NOT NULL CHECK (
        org_status IN ('Active', 'Inactive')
    ),
    org_archetype           text,
    specialty               text,
    address_line1           text,
    city                    text,
    state                   text,
    zip                     text,
    parent_org_id           text,
    parent_org_name         text,
    grandparent_org_id      text,
    grandparent_org_name    text,
    gpo_name                text,
    is_340b                 smallint NOT NULL DEFAULT 0 CHECK (is_340b IN (0, 1)),
    CONSTRAINT organizations_parent_fk
        FOREIGN KEY (parent_org_id)
        REFERENCES organizations(org_id)
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT organizations_grandparent_fk
        FOREIGN KEY (grandparent_org_id)
        REFERENCES organizations(org_id)
        DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE products (
    ndc                     text PRIMARY KEY,
    drug_name               text NOT NULL,
    generic_name            text NOT NULL,
    strength                text,
    form                    text,
    brand_flag              smallint NOT NULL CHECK (brand_flag IN (0, 1)),
    specialty               text,
    market_category         text,
    market_subcategory      text,
    unit_conversion_factor  numeric(12, 5) NOT NULL CHECK (unit_conversion_factor >= 0),
    mg_equivalent           numeric(14, 5) CHECK (mg_equivalent >= 0)
);

CREATE TABLE zip_territory (
    zip                 text PRIMARY KEY,
    state               text NOT NULL,
    territory_number    text NOT NULL,
    territory_name      text NOT NULL,
    region_number       text,
    region_name         text
);

CREATE TABLE users (
    user_id             text PRIMARY KEY,
    email               text NOT NULL UNIQUE,
    full_name           text NOT NULL,
    role                text NOT NULL CHECK (role IN ('exec', 'director', 'ram')),
    territory_name      text,
    region_name         text,
    can_view_wac        smallint NOT NULL DEFAULT 0 CHECK (can_view_wac IN (0, 1)),
    CONSTRAINT users_scope_matches_role CHECK (
        (role = 'exec' AND territory_name IS NULL AND region_name IS NULL AND can_view_wac = 1)
        OR (role = 'director' AND territory_name IS NULL AND region_name IS NOT NULL AND can_view_wac = 0)
        OR (role = 'ram' AND territory_name IS NOT NULL AND region_name IS NOT NULL AND can_view_wac = 0)
    )
);

CREATE TABLE sales (
    sale_id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id              text NOT NULL REFERENCES organizations(org_id),
    ndc                 text NOT NULL REFERENCES products(ndc),
    drug_name           text NOT NULL,
    data_source         text NOT NULL CHECK (
        data_source IN ('distributor', 'hub_dispense', 'market_data')
    ),
    brand_flag          smallint NOT NULL CHECK (brand_flag IN (0, 1)),
    pack_units          numeric(16, 3) CHECK (pack_units >= 0),
    total_mg            numeric(18, 3) CHECK (total_mg >= 0),
    wac                 numeric(18, 2) CHECK (wac >= 0),
    transaction_date    date NOT NULL,
    week_ending_date    date NOT NULL,
    state               text,
    specialty           text,
    period_wk           text NOT NULL,
    period_mo           text NOT NULL,
    period_qtr          text NOT NULL,
    wk_offset           integer NOT NULL CHECK (wk_offset >= 0),
    mo_offset           integer NOT NULL CHECK (mo_offset >= 0)
);

CREATE INDEX organizations_zip_idx
    ON organizations (zip);
CREATE INDEX organizations_parent_idx
    ON organizations (parent_org_id);
CREATE INDEX organizations_grandparent_idx
    ON organizations (grandparent_org_id);
CREATE INDEX zip_territory_territory_idx
    ON zip_territory (territory_name, zip);
CREATE INDEX zip_territory_region_idx
    ON zip_territory (region_name, zip);
CREATE INDEX sales_org_period_source_idx
    ON sales (org_id, mo_offset, data_source);
CREATE INDEX sales_ndc_period_source_idx
    ON sales (ndc, mo_offset, data_source);
CREATE INDEX sales_period_source_brand_idx
    ON sales (mo_offset, data_source, brand_flag);
CREATE INDEX sales_transaction_date_idx
    ON sales (transaction_date);

COMMENT ON TABLE sales IS
    'Synthetic pharmaceutical transactions from distributor, hub dispense, and market-data sources.';
COMMENT ON COLUMN sales.wac IS
    'Sensitive wholesale acquisition cost; database grants restrict this column to executives.';
COMMENT ON COLUMN users.can_view_wac IS
    'Defense-in-depth application flag. PostgreSQL column grants remain the hard boundary.';

COMMIT;
